[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "edu-pentest-toolbox"
version = "0.0.1"
description = "Not much to see here yet"
authors = [
	{ name = "Jonas Sundstrom", email = "jonas@kirilla.se" }
]
license = { file = "LICENSE" }
dependencies = [
	"argparse"
] 
classifiers = [
	# classifiers?
]

[project.entry-points.console_scripts]
hello = "hello.main:main"
argparser = "argparser.main:main"
